#!/bin/sh
#
# Entrypoint script for nginx-spnego auth-gateway
# - Waits for keytab to be available (generated by DC)
# - Generates self-signed TLS certificates if they don't exist
# - Starts NGINX
#

set -e

# -----------------------
# Configuration
# -----------------------
CERT_DIR="/etc/nginx/ssl"
CERT_FILE="${CERT_DIR}/nginx.crt"
KEY_FILE="${CERT_DIR}/nginx.key"
HOSTNAME="${SSL_HOSTNAME:-proxy.samdom.example.com}"

KEYTAB_PATH="${KEYTAB_PATH:-/etc/nginx/keytab/nginx.keytab}"
KEYTAB_WAIT_TIMEOUT="${KEYTAB_WAIT_TIMEOUT:-120}"
KEYTAB_WAIT_INTERVAL=2

# -----------------------
# Wait for keytab to be available
# -----------------------
echo "Waiting for keytab at ${KEYTAB_PATH}..."
elapsed=0
while [ ! -f "${KEYTAB_PATH}" ]; do
    sleep "${KEYTAB_WAIT_INTERVAL}"
    elapsed=$((elapsed + KEYTAB_WAIT_INTERVAL))
    if [ "$elapsed" -ge "$KEYTAB_WAIT_TIMEOUT" ]; then
        echo "ERROR: Keytab not found after ${KEYTAB_WAIT_TIMEOUT}s"
        echo "The domain controller should generate the keytab automatically."
        echo "Check DC logs: docker compose logs domain-controller | grep SPNEGO"
        exit 1
    fi
    echo "  Still waiting for keytab... (${elapsed}s/${KEYTAB_WAIT_TIMEOUT}s)"
done

echo "Keytab found at ${KEYTAB_PATH}"

# Verify keytab contents
if command -v klist >/dev/null 2>&1; then
    echo "Keytab contents:"
    klist -kte "${KEYTAB_PATH}" 2>&1 | while read -r line; do
        echo "  $line"
    done
else
    echo "WARN: klist not available, cannot verify keytab"
fi

# -----------------------
# Generate self-signed TLS certificate if needed
# -----------------------
if [ ! -f "${CERT_FILE}" ] || [ ! -f "${KEY_FILE}" ]; then
    echo "Generating self-signed certificate for ${HOSTNAME}..."
    mkdir -p "${CERT_DIR}"
    openssl req -x509 -nodes -days 3650 \
        -newkey rsa:2048 \
        -keyout "${KEY_FILE}" \
        -out "${CERT_FILE}" \
        -subj "/CN=${HOSTNAME}" \
        -addext "subjectAltName=DNS:${HOSTNAME},DNS:localhost,IP:127.0.0.1"
    chmod 644 "${CERT_FILE}"
    chmod 600 "${KEY_FILE}"
    echo "Certificate generated successfully:"
    echo "  Certificate: ${CERT_FILE}"
    echo "  Private Key: ${KEY_FILE}"
    echo ""
    echo "To import into Windows, copy nginx.crt from ./nginx-spnego/certs/ to your Windows client"
    echo "and import it into 'Trusted Root Certification Authorities'."
else
    echo "Using existing TLS certificate for ${HOSTNAME}"
fi

# -----------------------
# Start nginx
# -----------------------
echo "Starting NGINX with SPNEGO authentication..."
exec /usr/sbin/nginx -g "daemon off;"
